name: flutter_file_view
description: A file viewer plugin for Flutter, support local file and network link of Android, iOS.
version: 3.0.0
homepage: https://github.com/LiWenHui96
repository: https://github.com/LiWenHui96/flutter_file_view
issue_tracker: https://github.com/LiWenHui96/flutter_file_view/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.file.view
        pluginClass: FlutterFileViewPlugin
      ios:
        pluginClass: FlutterFileViewPlugin
